# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - "feat/*"

jobs:
  create-pull-request:
    # triggered when feat/* branch has been merged into master
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: true

      - name: Version Package
        id: versioning
        run: |
          npx changeset version
          echo "::set-output name=tag::v$(node -pe "require('./package.json').version")"
          git restore .

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: "chore: release ${{ steps.versioning.outputs.tag }}"
          title: "chore: release ${{ steps.versioning.outputs.tag }}"

