name: Release Package

on:
  pull_request:
    types:
      - closed
    branches: # target branch
      - master

jobs:
  release-package:
    # triggered when a branch starts with changeset-release/* has been merged into master
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'changeset-release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: true

      - name: Publish to npm
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: npx changeset version
