name: Release Package

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  pull-requests: write
  contents: write

jobs:
  release-package:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - uses: pnpm/action-setup@v6.0.8
        with:
          run_install: true

      - name: Version Package
        id: versioning
        run: |
          pnpm changeset version
          echo "tag=v$(node -pe "require('./package.json').version")" >> "$GITHUB_OUTPUT"
          git restore .

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          commit: "chore: release ${{ steps.versioning.outputs.tag }}"
          title: "chore: release ${{ steps.versioning.outputs.tag }}"
